import { readFile } from 'node:fs/promises';

// Windows addons must not import Node-API from a fixed module such as NODE.EXE: hosts like Electron export the
// same functions from their own executable, and binding to NODE.EXE either fails to load or pulls a second Node.js
// runtime into the process. Instead of an import library, Marmotta links the source generated here. It defines the
// import pointers and call stubs itself and binds them to the host process when the addon is loaded.

const symbolPattern = /^[A-Za-z_][A-Za-z0-9_]*$/;

export async function readDefSymbols(defPath: string): Promise<string[]> {
  const lines = (await readFile(defPath, 'utf8')).split(/\r?\n/).map((line) => line.trim());
  const start = lines.findIndex((line) => line.toUpperCase() === 'EXPORTS');
  return lines.slice(start + 1)
    .map((line) => line.split(/\s+/)[0] ?? '')
    .filter((symbol) => symbolPattern.test(symbol));
}

export function hostImportsSource(symbols: string[]): string {
  const list = symbols.map((symbol) => `  X(${symbol}) \\`).join('\n');
  return String.raw`/* Generated by Marmotta: binds Node-API imports to the host process. */
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>

#define MARMOTTA_NAPI_SYMBOLS(X) \
${list}

#if defined(__i386__) || defined(_M_IX86)
#define MARMOTTA_PREFIX "_"
#else
#define MARMOTTA_PREFIX ""
#endif

static void marmotta_missing_symbol(void) {
  fputs("Marmotta: this addon called a Node-API function that the host process does not export\n", stderr);
  abort();
}

/* Import pointers used by __declspec(dllimport) calls, as an import library would provide. */
#define X(name) void *marmotta_imp_##name __asm__("__imp_" MARMOTTA_PREFIX #name) = (void *)marmotta_missing_symbol;
MARMOTTA_NAPI_SYMBOLS(X)
#undef X

/* Call stubs for sources that declare Node-API functions without __declspec(dllimport). */
#if defined(__x86_64__) || defined(_M_X64)
#define X(name) __asm__(".text\n.globl " #name "\n.def " #name "; .scl 2; .type 32; .endef\n.p2align 4\n" \
  #name ":\n  jmpq *__imp_" #name "(%rip)\n");
#elif defined(__aarch64__) || defined(_M_ARM64)
#define X(name) __asm__(".text\n.globl " #name "\n.def " #name "; .scl 2; .type 32; .endef\n.p2align 2\n" \
  #name ":\n  adrp x16, __imp_" #name "\n  ldr x16, [x16, :lo12:__imp_" #name "]\n  br x16\n");
#elif defined(__i386__) || defined(_M_IX86)
#define X(name) __asm__(".text\n.globl _" #name "\n.def _" #name "; .scl 2; .type 32; .endef\n.p2align 4\n" \
  "_" #name ":\n  jmp *__imp__" #name "\n");
#else
#error "Marmotta does not support this Windows architecture"
#endif
MARMOTTA_NAPI_SYMBOLS(X)
#undef X

static FARPROC marmotta_lookup(HMODULE *modules, size_t count, const char *name) {
  for (size_t index = 0; index < count; index++) {
    FARPROC address = modules[index] ? GetProcAddress(modules[index], name) : NULL;
    if (address) return address;
  }
  return NULL;
}

/* Runs on DLL_PROCESS_ATTACH, before the host calls the addon's module initializer. */
__attribute__((constructor(101))) static void marmotta_bind_host(void) {
  /* node.exe and Electron export Node-API from the executable; embedders may use a shared Node.js library. */
  HMODULE modules[] = { GetModuleHandleW(NULL), GetModuleHandleW(L"libnode.dll"), GetModuleHandleW(L"node.dll") };
  size_t count = sizeof(modules) / sizeof(modules[0]);
  FARPROC address;
#define X(name) \
  if ((address = marmotta_lookup(modules, count, #name)) != NULL) marmotta_imp_##name = (void *)address;
  MARMOTTA_NAPI_SYMBOLS(X)
#undef X
}
`;
}
